<?php
declare(strict_types=1);

/**
 * Seed: Louvolite "Best Fit" truck tables for Vogue vertical blinds.
 *
 * Digitises Louvolite's official Best Fit charts (89mm louvres) so the build
 * engine can pick the truck count + carrier size by best fit instead of a fitter
 * reading the chart by hand. Five tables, one per operation:
 *   vogue_ow_cord      One Way Cord Operated        (LL sheet "PHYSICAL ONE WAY")
 *   vogue_ow_wand      One Way Mono Command / wand  (LL sheet "mono one way")
 *   vogue_split_cord   Split Draw Cord Operated      (LL sheet "split")
 *   vogue_split_1wand  Split Draw Mono, 1 Wand       (LL sheet "PHYSICALSPLIT DRAW")
 *   vogue_split_2wand  Split Draw Mono, 2 Wands      (LL sheet "mono split draw 2 wands")
 *
 * SOURCE OF TRUTH (2026-09-07): transcribed programmatically (scratchpad/
 * gen_bestfit.py) straight from Louvolite's supplied workbook
 *   T:\Beverley Blinds Trade\2026 Price Lists\Suppliers\Louvolite\Best Fit Charts.xls
 * — so these are Louvolite's exact cell values, not a hand-read of a PDF. This
 * supersedes the earlier transcription, which was truncated (one-way tables
 * stopped at 34-36 trucks) and carried a few INTERPOLATED 87mm cells (the old
 * PDF printed 87 = 85 for split-1wand rows 50+; Louvolite's workbook gives the
 * true distinct values). Only the 89mm-louvre columns (carrier sizes 83/85/87/89)
 * are digitised; Louvolite's parallel 127mm-louvre block is not used by Beverley.
 *
 * Each row's key is "count|size" (truck count | carrier size mm) and its value is
 * the maximum blind width that combination covers. The engine's BESTFIT() returns
 * the row with the smallest value >= the blind width (least oversail):
 *   Trucks     = BESTFIT("vogue_ow_cord", Width, 1)
 *   Truck_Size = BESTFIT("vogue_ow_cord", Width, 2)
 *
 * A null cell = a size Louvolite leaves blank in their own chart (only split-cord
 * carrier 72 does this, at 85/87 — widths of ~5.2m that can't exist anyway: a
 * single headrail maxes at 5000mm / 5m stock). Null cells are skipped, so BESTFIT
 * simply never offers that (count|size) combo. Coverage runs to carrier 72
 * (~5.5m) for completeness; enforce the real 5000mm ceiling on the product, not here.
 *
 * Idempotent (upsert into allowance_rows). Run via web: /seed_vogue_bestfit.php.
 */

require_once __DIR__ . '/bootstrap.php';

if (PHP_SAPI !== 'cli') {
    require_once __DIR__ . '/auth/middleware.php';
    requireSuperAdmin();
    header('Content-Type: text/plain; charset=utf-8');
}

ini_set('display_errors', '1');
error_reporting(E_ALL);

$pdo = db();
$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

$SIZES = [83, 85, 87, 89];

// count => [w83, w85, w87, w89] (max width covered, 89mm louvres). null = blank in
// Louvolite's chart. Generated by scratchpad/gen_bestfit.py from Best Fit Charts.xls.
$T = [];

$T['vogue_ow_cord'] = [
    2=>[178,180,182,184], 3=>[248,252,256,260], 4=>[317,323,330,336], 5=>[387,395,404,412],
    6=>[456,467,478,488], 7=>[526,539,553,564], 8=>[595,610,627,640], 9=>[665,682,701,716],
    10=>[734,754,775,792], 11=>[804,825,849,868], 12=>[873,897,923,944], 13=>[943,969,997,1020],
    14=>[1012,1040,1071,1096], 15=>[1082,1112,1145,1172], 16=>[1151,1184,1219,1248], 17=>[1221,1256,1294,1324],
    18=>[1290,1327,1368,1400], 19=>[1360,1399,1442,1476], 20=>[1429,1471,1516,1552], 21=>[1499,1542,1590,1628],
    22=>[1568,1614,1664,1704], 23=>[1638,1686,1738,1780], 24=>[1707,1757,1812,1856], 25=>[1777,1829,1886,1932],
    26=>[1846,1901,1960,2008], 27=>[1916,1973,2035,2084], 28=>[1985,2044,2109,2160], 29=>[2055,2116,2183,2236],
    30=>[2124,2188,2257,2312], 31=>[2194,2259,2331,2388], 32=>[2263,2331,2405,2464], 33=>[2333,2403,2479,2540],
    34=>[2402,2474,2553,2616], 35=>[2472,2546,2627,2692], 36=>[2541,2618,2701,2768], 37=>[2611,2690,2776,2844],
    38=>[2680,2761,2850,2920], 39=>[2750,2833,2924,2996], 40=>[2819,2905,2998,3072], 41=>[2889,2976,3072,3148],
    42=>[2958,3048,3146,3224], 43=>[3028,3120,3220,3300], 44=>[3097,3191,3294,3376], 45=>[3167,3263,3368,3452],
    46=>[3236,3335,3442,3528], 47=>[3306,3407,3517,3604], 48=>[3375,3478,3591,3680], 49=>[3445,3550,3665,3756],
    50=>[3514,3622,3739,3832], 51=>[3584,3693,3813,3908], 52=>[3654,3765,3887,3984], 53=>[3723,3837,3961,4060],
    54=>[3793,3908,4035,4136], 55=>[3862,3980,4109,4212], 56=>[3932,4052,4183,4288], 57=>[4001,4124,4258,4364],
    58=>[4071,4195,4332,4440], 59=>[4140,4267,4406,4516], 60=>[4210,4339,4480,4592], 61=>[4279,4410,4554,4668],
    62=>[4349,4482,4628,4744], 63=>[4418,4554,4702,4820], 64=>[4488,4625,4776,4896], 65=>[4557,4697,4850,4972],
    66=>[4627,4769,4924,5048], 67=>[4696,4840,4999,5124], 68=>[4766,4912,5073,5200], 69=>[4835,4984,5147,5276],
    70=>[4905,5056,5221,5352], 71=>[4974,5127,5295,5428], 72=>[5044,5199,5369,5504],
];

$T['vogue_ow_wand'] = [
    2=>[148,150,152,154], 3=>[218,222,226,230], 4=>[287,293,300,306], 5=>[357,365,374,382],
    6=>[426,437,448,458], 7=>[496,509,523,534], 8=>[565,580,597,610], 9=>[635,652,671,686],
    10=>[704,724,745,762], 11=>[774,795,819,838], 12=>[843,867,893,914], 13=>[913,939,967,990],
    14=>[982,1010,1041,1066], 15=>[1052,1082,1115,1142], 16=>[1121,1154,1189,1218], 17=>[1191,1226,1264,1294],
    18=>[1260,1297,1338,1370], 19=>[1330,1369,1412,1446], 20=>[1399,1441,1486,1522], 21=>[1469,1512,1560,1598],
    22=>[1538,1584,1634,1674], 23=>[1608,1656,1708,1750], 24=>[1677,1727,1782,1826], 25=>[1747,1799,1856,1902],
    26=>[1816,1871,1930,1978], 27=>[1886,1943,2005,2054], 28=>[1955,2014,2079,2130], 29=>[2025,2086,2153,2206],
    30=>[2094,2158,2227,2282], 31=>[2164,2229,2301,2358], 32=>[2233,2301,2375,2434], 33=>[2303,2373,2449,2510],
    34=>[2372,2444,2523,2586], 35=>[2442,2516,2597,2662], 36=>[2511,2588,2671,2738], 37=>[2581,2660,2746,2814],
    38=>[2650,2731,2820,2890], 39=>[2720,2803,2894,2966], 40=>[2789,2875,2968,3042], 41=>[2859,2946,3042,3118],
    42=>[2928,3018,3116,3194], 43=>[2998,3090,3190,3270], 44=>[3067,3161,3264,3346], 45=>[3137,3233,3338,3422],
    46=>[3206,3305,3412,3498], 47=>[3276,3377,3487,3574], 48=>[3345,3448,3561,3650], 49=>[3415,3520,3635,3726],
    50=>[3484,3592,3709,3802], 51=>[3554,3663,3783,3878], 52=>[3624,3735,3857,3954], 53=>[3693,3807,3931,4030],
    54=>[3763,3878,4005,4106], 55=>[3832,3950,4079,4182], 56=>[3902,4022,4153,4258], 57=>[3971,4094,4228,4334],
    58=>[4041,4165,4302,4410], 59=>[4110,4237,4376,4486], 60=>[4180,4309,4450,4562], 61=>[4249,4380,4524,4638],
    62=>[4319,4452,4598,4714], 63=>[4388,4524,4672,4790], 64=>[4458,4595,4746,4866], 65=>[4527,4667,4820,4942],
    66=>[4597,4739,4894,5018], 67=>[4666,4810,4969,5094], 68=>[4736,4882,5043,5170], 69=>[4805,4954,5117,5246],
    70=>[4875,5026,5191,5322], 71=>[4944,5097,5265,5398], 72=>[5014,5169,5339,5474],
];

$T['vogue_split_cord'] = [
    2=>[158,160,162,164], 4=>[304,308,312,316], 6=>[445,453,461,469], 8=>[585,597,609,621],
    10=>[726,742,758,774], 12=>[867,887,907,927], 14=>[1007,1031,1055,1079], 16=>[1148,1176,1204,1232],
    18=>[1288,1320,1352,1384], 20=>[1429,1465,1501,1537], 22=>[1570,1610,1650,1690], 24=>[1710,1754,1798,1842],
    26=>[1851,1899,1947,1995], 28=>[1991,2043,2095,2147], 30=>[2132,2188,2244,2300], 32=>[2273,2333,2393,2453],
    34=>[2413,2477,2541,2605], 36=>[2554,2622,2690,2758], 38=>[2694,2766,2838,2910], 40=>[2835,2911,2987,3063],
    42=>[2976,3056,3136,3216], 44=>[3116,3200,3284,3368], 46=>[3257,3345,3433,3521], 48=>[3397,3489,3581,3673],
    50=>[3538,3634,3730,3826], 52=>[3679,3779,3879,3979], 54=>[3819,3923,4027,4131], 56=>[3960,4068,4176,4284],
    58=>[4100,4212,4324,4436], 60=>[4241,4357,4473,4589], 62=>[4382,4502,4622,4742], 64=>[4522,4646,4770,4894],
    66=>[4663,4791,4919,5047], 68=>[4803,4935,5067,5199], 70=>[4944,5080,5216,5352], 72=>[5085,null,null,5505],
];

$T['vogue_split_1wand'] = [
    2=>[158,160,162,164], 4=>[297,304,310,316], 6=>[437,447,458,469], 8=>[576,591,607,621],
    10=>[715,735,755,774], 12=>[855,878,903,927], 14=>[994,1022,1051,1079], 16=>[1133,1166,1199,1232],
    18=>[1272,1309,1348,1384], 20=>[1412,1453,1496,1537], 22=>[1551,1597,1644,1690], 24=>[1690,1740,1792,1842],
    26=>[1830,1884,1940,1995], 28=>[1969,2028,2089,2147], 30=>[2108,2172,2237,2300], 32=>[2248,2315,2385,2453],
    34=>[2387,2459,2533,2605], 36=>[2526,2603,2681,2758], 38=>[2665,2746,2830,2910], 40=>[2805,2890,2978,3063],
    42=>[2944,3034,3126,3216], 44=>[3083,3177,3274,3368], 46=>[3223,3321,3422,3521], 48=>[3362,3465,3571,3673],
    50=>[3501,3608,3719,3826], 52=>[3641,3752,3867,3979], 54=>[3780,3896,4015,4131], 56=>[3919,4039,4163,4284],
    58=>[4058,4183,4312,4436], 60=>[4198,4327,4460,4589], 62=>[4337,4470,4608,4742], 64=>[4476,4614,4756,4894],
    66=>[4616,4758,4904,5047], 68=>[4755,4901,5053,5199], 70=>[4894,5045,5201,5352], 72=>[5034,5189,5349,5505],
];

$T['vogue_split_2wand'] = [
    2=>[128,130,132,134], 4=>[267,274,280,286], 6=>[407,417,428,439], 8=>[546,561,577,591],
    10=>[685,705,725,744], 12=>[825,848,873,897], 14=>[964,992,1021,1049], 16=>[1103,1136,1169,1202],
    18=>[1242,1279,1318,1354], 20=>[1382,1423,1466,1507], 22=>[1521,1567,1614,1660], 24=>[1660,1710,1762,1812],
    26=>[1800,1854,1910,1965], 28=>[1939,1998,2059,2117], 30=>[2078,2142,2207,2270], 32=>[2218,2285,2355,2423],
    34=>[2357,2429,2503,2575], 36=>[2496,2573,2651,2728], 38=>[2635,2716,2800,2880], 40=>[2775,2860,2948,3033],
    42=>[2914,3004,3096,3186], 44=>[3053,3147,3244,3338], 46=>[3193,3291,3392,3491], 48=>[3332,3435,3541,3643],
    50=>[3471,3578,3689,3796], 52=>[3611,3722,3837,3949], 54=>[3750,3866,3985,4101], 56=>[3889,4009,4133,4254],
    58=>[4028,4153,4282,4406], 60=>[4168,4297,4430,4559], 62=>[4307,4440,4578,4712], 64=>[4446,4584,4726,4864],
    66=>[4586,4728,4874,5017], 68=>[4725,4871,5023,5169], 70=>[4864,5015,5171,5322], 72=>[5004,5159,5319,5475],
];

// Self-check: across each row the PRESENT (non-null) sizes must strictly increase.
$warnings = [];
foreach ($T as $name => $rows) {
    foreach ($rows as $count => $vals) {
        $prev = null;
        foreach ($vals as $v) {
            if ($v === null) continue;
            if ($prev !== null && $v <= $prev) {
                $warnings[] = "{$name} count {$count}: not increasing (" . implode(',', array_map(static fn ($x) => $x ?? '—', $vals)) . ")";
            }
            $prev = $v;
        }
    }
}

$upsert = $pdo->prepare(
    "INSERT INTO allowance_rows (table_name, key_norm, keys_display, value, seq)
     VALUES (?, ?, ?, ?, ?)
     ON DUPLICATE KEY UPDATE keys_display = VALUES(keys_display), value = VALUES(value), seq = VALUES(seq)"
);

// Reset each table to Louvolite's authoritative figures. These five tables are
// wholly owned by this seed, so clearing first drops any stale cells the previous
// (interpolated/truncated) transcription left behind — notably split-cord 72|85 &
// 72|87, now blank in Louvolite's own chart. NB: this also discards any manual
// edits made via the Allowances screen to these five tables (intended — we're
// restoring the supplier's official numbers).
$del = $pdo->prepare('DELETE FROM allowance_rows WHERE table_name = ?');

$total = 0;
foreach ($T as $name => $rows) {
    $del->execute([$name]);
    $seq = 0;
    foreach ($rows as $count => $vals) {
        foreach ($SIZES as $si => $size) {
            if (!isset($vals[$si]) || $vals[$si] === null) continue;   // blank in Louvolite's chart
            $key  = $count . '|' . $size;               // "count|size"
            $disp = $count . ' · ' . $size;             // "24 · 87"
            $upsert->execute([$name, $key, $disp, (float) $vals[$si], $seq++]);
            $total++;
        }
    }
    echo sprintf("  %-20s %d rows\n", $name, $seq);
}

echo "\nSeeded {$total} best-fit rows across " . count($T) . " tables.\n";
if ($warnings) {
    echo "\n⚠ MONOTONICITY WARNINGS (check these against the chart):\n";
    foreach ($warnings as $w) echo "  - {$w}\n";
} else {
    echo "Self-check: all rows increase across present truck sizes. \n";
}
echo "\nReference in a build rule with BESTFIT(\"<table>\", Width, 1) for the count,\n";
echo "or 2 for the carrier size. Verify a few widths against the Best Fit chart.\n";
